routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'HomeController@home', 'as' => 'front_end.home']);
Route::get('/shop', ['uses' => 'HomeController@getShop', 'as' => 'front_end.shop']);

Route::get('/cham-soc-cay', ['uses' => 'HomeController@getTakeCare', 'as' => 'front_end.take_care']);

Route::get('/lien-he', ['uses' => 'HomeController@getContact', 'as' => 'front_end.contact']);

Route::get('/cay/{slug}', ['uses' => 'HomeController@productDetail', 'as' => 'post.show']);

Auth::routes();

Route::group(['middleware' => 'auth', 'prefix' => 'p-admin'], function(){
    Route::get('/', function(){
        return redirect()->route('posts.index');
    });
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');

});

resources/views/admin/layouts/partials/header.blade.php
<header class="header">
    <a href="/" class="logo">
        <img src="/images/logo_luatdan.png" style="max-width: 45px;" alt="logo">
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <div>
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <div class="responsive_nav"></div>
            </a>
        </div>
        <div class="navbar-right">
            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">

                        <div class="riot">
                            <div>
                                {!! Form::open(['route' => 'logout', 'method' => 'POST']) !!}
                                    {!! Form::submit('Đăng xuất', ['class' => 'btn btn-primary']) !!}
                                {!! Form::close() !!}
                            </div>
                        </div>


                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/partials/sidebar.blade.php
<aside class="left-side sidebar-offcanvas">
    <section class="sidebar ">
        <div class="page-sidebar  sidebar-nav">

            <div class="clearfix"></div>
            <!-- BEGIN SIDEBAR MENU -->
            <ul class="page-sidebar-menu" id="menu">
                <li class="@if(Request::is('p-admin/categories') || Request::is('p-admin/categories/*')) active @endif">
                    <a href="#">
                        <i class="livicon" data-name="medal" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                        <span class="title">Danh mục</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="{{ route('categories.index') }}">
                                <i class="fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('categories.create') }}">
                                <i class="fa fa-angle-double-right"></i>
                                Tạo mới
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="@if(Request::is('p-admin/posts') || Request::is('p-admin/posts/*')) active @endif">
                    <a href="#">
                        <i class="livicon" data-name="medal" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                        <span class="title">Sản phẩm</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="{{ route('posts.index') }}">
                                <i class="fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('posts.create') }}">
                                <i class="fa fa-angle-double-right"></i>
                                Tạo mới
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="@if(Request::is('p-admin/users') || Request::is('p-admin/users/*')) active @endif">
                    <a href="#">
                        <i class="livicon" data-name="medal" data-size="18" data-c="#00bc8c" data-hc="#00bc8c" data-loop="true"></i>
                        <span class="title">Thành viên</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="{{ route('users.index') }}">
                                <i class="fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.create') }}">
                                <i class="fa fa-angle-double-right"></i>
                                Tạo mới
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
    </section>
    <!-- /.sidebar -->
</aside>